# Generated by Django 3.0.4 on 2020-04-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_auto_20200426_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfiteatro',
            fields=[
                ('edificio', models.CharField(max_length=45)),
                ('andar', models.CharField(max_length=45)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inscricao.Espaco')),
            ],
            options={
                'db_table': 'anfiteatro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arlivre',
            fields=[
                ('descricao', models.CharField(max_length=255)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inscricao.Espaco')),
            ],
            options={
                'db_table': 'arlivre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtividadeHasMaterial',
            fields=[
                ('atividade_idatividade', models.OneToOneField(db_column='Atividade_idAtividade', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inscricao.Atividade')),
            ],
            options={
                'db_table': 'atividade_has_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('preferencia', models.CharField(blank=True, max_length=255, null=True)),
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inscricao.Utilizador')),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorHasHorario',
            fields=[
                ('colaborador_has_horario_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'colaborador_has_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorHasUnidadeOrganica',
            fields=[
                ('colaborador_has_unidade_organica_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'colaborador_has_unidade_organica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inscricao.Utilizador')),
            ],
            options={
                'db_table': 'coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('idtarefa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('concluida', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
            ],
            options={
                'db_table': 'tarefa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoordenadorHasDepartamento',
            fields=[
                ('coordenador_utilizador_idutilizador', models.OneToOneField(db_column='Coordenador_Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inscricao.Coordenador')),
            ],
            options={
                'db_table': 'coordenador_has_departamento',
                'managed': False,
            },
        ),
    ]
