# Generated by Django 3.0.3 on 2020-04-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('destino', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'destino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioHasDia',
            fields=[
                ('id_dia_hora', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'horario_has_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('origem', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'origem',
                'managed': False,
            },
        ),
    ]
