# Generated by Django 3.0.3 on 2020-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_destino_horariohasdia_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragem',
            fields=[
                ('paragem', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paragem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoHasHorarioHasDia',
            fields=[
                ('sessao_has_horario_has_dia_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sessao_has_horario_has_dia',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.DeleteModel(
            name='Origem',
        ),
    ]
