# Generated by Django 3.0.3 on 2020-04-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200421_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoHasSessao',
            fields=[
                ('inscricao_has_sessao_id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_inscritos', models.IntegerField()),
            ],
            options={
                'db_table': 'inscricao_has_sessao',
                'managed': False,
            },
        ),
    ]
