# Generated by Django 3.0.3 on 2020-03-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idatividade', models.AutoField(db_column='idAtividade', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('capacidade', models.IntegerField()),
                ('duracao', models.FloatField()),
                ('descricao', models.CharField(max_length=250)),
                ('validada', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('idcampus', models.AutoField(db_column='idCampus', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.AutoField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaAberto',
            fields=[
                ('ano', models.TextField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=120, null=True)),
                ('datainscricao', models.DateField()),
                ('emaildiaaberto', models.CharField(db_column='emailDiaAberto', max_length=120)),
                ('enderecopaginaweb', models.CharField(db_column='enderecoPaginaWeb', max_length=60)),
                ('datadiainscricaoatividadesinicio', models.DateField(db_column='dataDiainscricaoAtividadesInicio')),
                ('datadiaabertoinicio', models.DateField(db_column='dataDiaAbertoInicio')),
                ('datainscricaoatividadesfim', models.DateField(db_column='dataInscricaoAtividadesfim')),
                ('datadiaabertofim', models.DateField(db_column='dataDiaAbertofim')),
                ('datapropostaatividadeinicio', models.DateField(db_column='dataPropostaAtividadeInicio')),
                ('datapropostaatividadesfim', models.DateField(db_column='dataPropostaAtividadesFim')),
            ],
            options={
                'db_table': 'dia_aberto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('idescola', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('local', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'escola',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('idespaco', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'espaco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horainicio', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('nome', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('idinscricao', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.TextField()),
                ('local', models.CharField(max_length=45)),
                ('areacientifica', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmaterial', models.AutoField(db_column='idMaterial', primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idmenu', models.AutoField(db_column='idMenu', primary_key=True, serialize=False)),
                ('precoaluno', models.FloatField(db_column='precoAluno')),
                ('precoprofessor', models.FloatField(db_column='PrecoProfessor')),
                ('tipo', models.CharField(max_length=45)),
                ('menu', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('criadoem', models.DateTimeField()),
                ('idutilizadorenvia', models.IntegerField()),
                ('utilizadorrecebe', models.IntegerField()),
            ],
            options={
                'db_table': 'notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('idprato', models.AutoField(db_column='idPrato', primary_key=True, serialize=False)),
                ('nralomocosdisponiveis', models.IntegerField()),
                ('descricao', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'prato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('idsessao', models.AutoField(primary_key=True, serialize=False)),
                ('nrinscritos', models.IntegerField()),
                ('vagas', models.IntegerField()),
            ],
            options={
                'db_table': 'sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('idtarefa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('concluida', models.IntegerField()),
            ],
            options={
                'db_table': 'tarefa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.AutoField(primary_key=True, serialize=False)),
                ('capacidade', models.IntegerField()),
                ('identificacao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeOrganica',
            fields=[
                ('iduo', models.AutoField(db_column='idUO', primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'unidade_organica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('idutilizador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('telefone', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('username', models.CharField(db_column='userName', max_length=45)),
                ('validada', models.IntegerField()),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Utilizador')),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anfiteatro',
            fields=[
                ('edificio', models.CharField(max_length=45)),
                ('andar', models.CharField(max_length=45)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Espaco')),
            ],
            options={
                'db_table': 'anfiteatro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arlivre',
            fields=[
                ('descricao', models.CharField(max_length=45)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Espaco')),
            ],
            options={
                'db_table': 'arlivre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtividadeHasMaterial',
            fields=[
                ('atividade_idatividade', models.OneToOneField(db_column='Atividade_idAtividade', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Atividade')),
            ],
            options={
                'db_table': 'atividade_has_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('curso', models.CharField(max_length=45)),
                ('preferencia', models.CharField(blank=True, max_length=45, null=True)),
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Utilizador')),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Utilizador')),
            ],
            options={
                'db_table': 'coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscricaoColetiva',
            fields=[
                ('nresponsaveis', models.IntegerField()),
                ('turma', models.CharField(max_length=1)),
                ('inscricao_idinscricao', models.OneToOneField(db_column='inscricao_idinscricao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Inscricao')),
            ],
            options={
                'db_table': 'inscricao_coletiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscricaoHasPrato',
            fields=[
                ('inscricao_idinscricao', models.OneToOneField(db_column='inscricao_idinscricao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Inscricao')),
            ],
            options={
                'db_table': 'inscricao_has_prato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscricaoHasSessao',
            fields=[
                ('inscricao_idinscricao', models.OneToOneField(db_column='inscricao_idinscricao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Inscricao')),
            ],
            options={
                'db_table': 'inscricao_has_sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscricaoIndividual',
            fields=[
                ('nracompanhades', models.IntegerField()),
                ('inscricao_idinscricao', models.OneToOneField(db_column='inscricao_idinscricao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Inscricao')),
            ],
            options={
                'db_table': 'inscricao_individual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Utilizador')),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessorUniversitario',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Utilizador')),
            ],
            options={
                'db_table': 'professor_universitario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('edificio', models.CharField(max_length=45)),
                ('andar', models.CharField(max_length=45)),
                ('gabinete', models.CharField(blank=True, max_length=45, null=True)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Espaco')),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteHasHorario',
            fields=[
                ('transporte_idtransporte', models.OneToOneField(db_column='transporte_idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Transporte')),
            ],
            options={
                'db_table': 'transporte_has_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteHasInscricao',
            fields=[
                ('transporte_idtransporte', models.OneToOneField(db_column='transporte_idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Transporte')),
            ],
            options={
                'db_table': 'transporte_has_inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportePessoal',
            fields=[
                ('transporte_idtransporte', models.OneToOneField(db_column='transporte_idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Transporte')),
            ],
            options={
                'db_table': 'transporte_pessoal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteUniversitario',
            fields=[
                ('capacidade', models.IntegerField()),
                ('transporte_idtransporte', models.OneToOneField(db_column='transporte_idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Transporte')),
            ],
            options={
                'db_table': 'transporte_universitario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilizadorHasNotificacao',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Utilizador')),
            ],
            options={
                'db_table': 'utilizador_has_notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorHasHorario',
            fields=[
                ('colaborador_utilizador_idutilizador', models.OneToOneField(db_column='colaborador_Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Colaborador')),
            ],
            options={
                'db_table': 'colaborador_has_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorHasUnidadeOrganica',
            fields=[
                ('colaborador_utilizador_idutilizador', models.OneToOneField(db_column='colaborador_Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Colaborador')),
            ],
            options={
                'db_table': 'colaborador_has_unidade_organica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoordenadorHasDepartamento',
            fields=[
                ('coordenador_utilizador_idutilizador', models.OneToOneField(db_column='Coordenador_Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atividades.Coordenador')),
            ],
            options={
                'db_table': 'coordenador_has_departamento',
                'managed': False,
            },
        ),
    ]
