# Generated by Django 3.0.3 on 2020-04-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioHasDia',
            fields=[
                ('id_dia_hora', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'horario_has_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paragem',
            fields=[
                ('paragem', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paragem',
                'managed': False,
            },
        ),
    ]
