# Generated by Django 3.0.3 on 2020-04-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfiteatro',
            name='espaco_idespaco',
        ),
        migrations.RemoveField(
            model_name='arlivre',
            name='espaco_idespaco',
        ),
        migrations.RemoveField(
            model_name='atividadehasmaterial',
            name='atividade_idatividade',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='utilizador_idutilizador',
        ),
        migrations.DeleteModel(
            name='ColaboradorHasHorario',
        ),
        migrations.DeleteModel(
            name='ColaboradorHasUnidadeOrganica',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='utilizador_idutilizador',
        ),
        migrations.RemoveField(
            model_name='coordenadorhasdepartamento',
            name='coordenador_utilizador_idutilizador',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.DeleteModel(
            name='Anfiteatro',
        ),
        migrations.DeleteModel(
            name='Arlivre',
        ),
        migrations.DeleteModel(
            name='AtividadeHasMaterial',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='Coordenador',
        ),
        migrations.DeleteModel(
            name='CoordenadorHasDepartamento',
        ),
    ]
