# Generated by Django 3.0.3 on 2020-03-24 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('idcampus', models.AutoField(db_column='idCampus', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaAberto',
            fields=[
                ('ano', models.TextField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=120, null=True)),
                ('datainscricao', models.DateField()),
                ('emaildiaaberto', models.CharField(db_column='emailDiaAberto', max_length=120)),
                ('enderecopaginaweb', models.CharField(db_column='enderecoPaginaWeb', max_length=60)),
                ('datadiainscricaoatividadesinicio', models.DateField(db_column='dataDiainscricaoAtividadesInicio')),
                ('datadiaabertoinicio', models.DateField(db_column='dataDiaAbertoInicio')),
                ('datainscricaoatividadesfim', models.DateField(db_column='dataInscricaoAtividadesfim')),
                ('datadiaabertofim', models.DateField(db_column='dataDiaAbertofim')),
                ('datapropostaatividadeinicio', models.DateField(db_column='dataPropostaAtividadeInicio')),
                ('datapropostaatividadesfim', models.DateField(db_column='dataPropostaAtividadesFim')),
            ],
            options={
                'db_table': 'dia aberto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeOrganica',
            fields=[
                ('iduo', models.IntegerField(db_column='idUO', primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'unidade organica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('idutilizador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('telefone', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('username', models.CharField(db_column='userName', max_length=45)),
                ('validada', models.IntegerField()),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Utilizador')),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('curso', models.CharField(max_length=45)),
                ('preferencia', models.CharField(blank=True, max_length=45, null=True)),
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Utilizador')),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Utilizador')),
            ],
            options={
                'db_table': 'coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Utilizador')),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessorUniversitario',
            fields=[
                ('utilizador_idutilizador', models.OneToOneField(db_column='Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Utilizador')),
            ],
            options={
                'db_table': 'professor universitario',
                'managed': False,
            },
        ),
    ]
