# Generated by Django 3.0.3 on 2020-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('idutilizador', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(db_column='userName', max_length=45)),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
    ]
