# Generated by Django 3.0.3 on 2020-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.AutoField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='professoruniversitario',
            table='professor_universitario',
        ),
    ]
