# Generated by Django 3.0.3 on 2020-04-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200329_1420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diaaberto',
            table='dia_aberto',
        ),
        migrations.AlterModelTable(
            name='unidadeorganica',
            table='unidade_organica',
        ),
    ]
