# Generated by Django 3.0.4 on 2020-04-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_atividade_dia_escola_espaco_inscricao_inscricaocoletiva_inscricaoindividual_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfiteatro',
            fields=[
                ('edificio', models.CharField(max_length=45)),
                ('andar', models.CharField(max_length=45)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Espaco')),
            ],
            options={
                'db_table': 'anfiteatro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arlivre',
            fields=[
                ('descricao', models.CharField(max_length=255)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Espaco')),
            ],
            options={
                'db_table': 'arlivre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtividadeHasMaterial',
            fields=[
                ('atividade_idatividade', models.OneToOneField(db_column='Atividade_idAtividade', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Atividade')),
            ],
            options={
                'db_table': 'atividade_has_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorHasHorario',
            fields=[
                ('colaborador_has_horario_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'colaborador_has_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorHasUnidadeOrganica',
            fields=[
                ('colaborador_has_unidade_organica_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'colaborador_has_unidade_organica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoordenadorHasDepartamento',
            fields=[
                ('coordenador_utilizador_idutilizador', models.OneToOneField(db_column='Coordenador_Utilizador_idutilizador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Coordenador')),
            ],
            options={
                'db_table': 'coordenador_has_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('hora', models.TimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioHasDia',
            fields=[
                ('id_dia_hora', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'horario_has_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscricaoHasPrato',
            fields=[
                ('inscricao_has_prato_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inscricao_has_prato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscricaoHasSessao',
            fields=[
                ('inscricao_has_sessao_id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_inscritos', models.IntegerField()),
            ],
            options={
                'db_table': 'inscricao_has_sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idmaterial', models.AutoField(db_column='idMaterial', primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idmenu', models.AutoField(db_column='idMenu', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('menu', models.CharField(max_length=45)),
                ('nralmocosdisponiveis', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('criadoem', models.DateTimeField()),
                ('idutilizadorenvia', models.IntegerField()),
                ('utilizadorrecebe', models.IntegerField()),
            ],
            options={
                'db_table': 'notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paragem',
            fields=[
                ('paragem', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'paragem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('idprato', models.AutoField(db_column='idPrato', primary_key=True, serialize=False)),
                ('nralmocos', models.IntegerField()),
                ('descricao', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'prato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('idresponsavel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'responsaveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('edificio', models.CharField(max_length=45)),
                ('andar', models.CharField(max_length=45)),
                ('gabinete', models.CharField(blank=True, max_length=45, null=True)),
                ('espaco_idespaco', models.OneToOneField(db_column='espaco_idespaco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Espaco')),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('idsessao', models.AutoField(primary_key=True, serialize=False)),
                ('nrinscritos', models.IntegerField()),
                ('vagas', models.IntegerField()),
            ],
            options={
                'db_table': 'sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoHasHorarioHasDia',
            fields=[
                ('sessao_has_horario_has_dia_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sessao_has_horario_has_dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.AutoField(primary_key=True, serialize=False)),
                ('capacidade', models.IntegerField()),
                ('identificacao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteHasHorario',
            fields=[
                ('id_transporte_has_horario', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'transporte_has_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteHasInscricao',
            fields=[
                ('transporte_has_inscricao_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_passageiros', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transporte_has_inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilizadorHasNotificacao',
            fields=[
                ('utilizador_has_notificacao_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'utilizador_has_notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportePessoal',
            fields=[
                ('transporte_idtransporte', models.OneToOneField(db_column='transporte_idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Transporte')),
            ],
            options={
                'db_table': 'transporte_pessoal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteUniversitario',
            fields=[
                ('capacidade', models.IntegerField()),
                ('transporte_idtransporte', models.OneToOneField(db_column='transporte_idtransporte', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.Transporte')),
            ],
            options={
                'db_table': 'transporte_universitario',
                'managed': False,
            },
        ),
    ]
